sourcebot-dev/sourcebot

- package.json
- src/app/navigationMenu.tsx
- src/app/page.tsx
- src/app/repos/columns.tsx
- src/app/repositoryCarousel.tsx
- src/components/ui/carousel.tsx
- src/lib/schemas.ts
- yarn.lock
Design:
https://github.com/user-attachments/assets/82adc2bb-190a-4c0a-bafc-da5e48a96d32
When there are no indexed repositories:
> Add repo carousel and "how to search" section to homepage

- CHANGELOG.md
- Dockerfile
- README.md
- entrypoint.sh
- example-config.json
Adds override env vars `GITLAB_HOSTNAME` and `GITHUB_HOSTNAME` to support authenticating against self-hosted GitLab / GitHub instances.
Fixes #20
> Add env vars for overriding GitHub / GitLab hostnames in the `.netrc` file.

- src/app/search/components/codePreviewPanel/index.tsx
- src/app/search/components/searchResultsPanel/fileMatch.tsx
- src/lib/utils.ts
see https://web.dev/articles/base64-encoding#strings_in_unicode_and_javascript
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
https://stackoverflow.com/questions/8936984/uint8array-to-string-in-javascript
> fix: fix  javascript btoa function can not handle Unicode strings issue

- CHANGELOG.md
- packages/backend/src/index.ts
- packages/backend/src/utils.ts
Added support for specifying urls for the `--configPath` option in the backend.
> Add support for remote configs

- CHANGELOG.md
- packages/web/components.json
- packages/web/package.json
- packages/web/src/app/layout.tsx
- packages/web/src/app/page.tsx
- packages/web/src/app/upgradeToast.tsx
- packages/web/src/components/hooks/use-toast.ts
- packages/web/src/components/ui/toast.tsx
- packages/web/src/components/ui/toaster.tsx
- yarn.lock
Added a toast notification that will popup when a new version is available. The toast is limited to popping up once every 24 hours. The upgrade button takes the user to the [latest release](https://github.com/sourcebot-dev/sourcebot/releases/latest).
> Version upgrade toast

- CHANGELOG.md
- packages/backend/src/gitlab.ts
- packages/backend/src/schemas/v2.ts
- schemas/v2/index.json
Previously, we were using the `owned=true` query parameter for our requests to [GET /groups/:id/projects](https://docs.gitlab.com/ee/api/groups.html#list-projects) and [GET /users/:user_id/projects](https://docs.gitlab.com/ee/api/projects.html#list-a-users-projects) which "Limits by projects explicitly owned by the current user.". This becomes an issue when the provided access token isn't associated with a user with type `owner` for all projects in the group / user.
This PR removes this constraint.
Fixes #50
> [Fix] Change GitLab syncing behaviour for `groups` and `users` to include projects that are _not_ owned by the token

- packages/backend/src/gitlab.ts
> GitLab: include subgroups when filtering on groups

- .vscode/extensions.json
- .vscode/settings.json
- CHANGELOG.md
- packages/web/package.json
- packages/web/src/app/search/components/codePreviewPanel/index.tsx
- packages/web/src/app/search/components/filterPanel/index.tsx
- packages/web/src/app/search/components/searchResultsPanel/codePreview.tsx
- packages/web/src/app/search/components/searchResultsPanel/fileMatch.tsx
- packages/web/src/app/search/components/searchResultsPanel/fileMatchContainer.tsx
- packages/web/src/app/search/components/searchResultsPanel/index.tsx
- packages/web/src/app/search/components/searchResultsPanel/lightweightCodeMirror.tsx
- packages/web/src/app/search/page.tsx
- packages/web/src/hooks/useSyntaxHighlightingExtension.ts
- yarn.lock
This PR improves the perf of the search result list, resulting in a ~10x speedup for search results to render. This is achieved using [react-virtual](https://tanstack.com/virtual/latest), which allows us to only render the portion of the list that is visible (plus some buffer).
> Improve rendering performance of search results

- CHANGELOG.md
- Dockerfile
- README.md
- configs/auth.json
- configs/basic.json
- configs/filter.json
- configs/local-repo.json
- configs/self-hosted.json
- packages/backend/src/db.ts
- packages/backend/src/git.ts
- packages/backend/src/gitea.ts
- packages/backend/src/github.ts
- packages/backend/src/gitlab.ts
- packages/backend/src/index.ts
- packages/backend/src/local.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- packages/backend/src/utils.ts
- packages/backend/src/zoekt.ts
- packages/web/src/app/repos/columns.tsx
- packages/web/src/app/repos/repositoryTable.tsx
- packages/web/src/lib/schemas.ts
- schemas/v2/index.json
This PR expands the configuration schema to support local directories. For example:
```jsonc
{
"repos": [
{
"type": "local",
"path": "/path/to/my/repo",
"watch": true,
"exclude": {
"paths": [
".git",
"node_modules"
]
}
}
]
}
```
Fixes #19
> Local directory support

- .gitignore
- configs/filter.json
- packages/backend/src/utils.test.ts
- packages/backend/src/utils.ts
- schemas/v2/index.json
> Exclude repos by glob

- packages/backend/src/schemas/v2.ts
- packages/backend/src/zoekt.ts
Previously, indexing was failing for empty repositories with `getCommit("refs/heads/", "HEAD"): reference not found`. This PR adds the [allow_missing_branches](https://github.com/sourcebot-dev/zoekt/blob/6d9547e7d0e67da091f26d9b3e03b4d09ce9ad69/cmd/zoekt-git-index/main.go#L36) option to the `zoekt-git-index` call. This will make it s.t., a ref is skipped if it cannot be found.
Note for issue #59 : this might has the side-effect where if HEAD actually does reference something that exists, we will now silently fail (HEAD will not be indexed). We should follow up by raising a warning message when HEAD doesn't reference anything.
> Fix issue with empty branches

- CHANGELOG.md
- configs/basic.json
- packages/backend/src/gitlab.ts
- packages/backend/src/schemas/v2.ts
- schemas/v2/index.json
This PR adds the option `all` to the GitLab index config. When enabled, all projects within the GitLab instance that are visible to the provided `token` (if any) will be indexed.
Example:
```jsonc
{
"repos": [
{
"type": "gitlab",
"url": "https://gitlab.example.com",
"token": {
"env": "GITLAB_TOKEN"
},
"all": true
}
]
}
```
Note: I've made this option no-op when using https://gitlab.com . I tested it, and if `all` is enabled, **all projects hosted on gitlab.com are fetched**, resulting in the get request never completing. We could use the `visibility` param of the [GET /projects](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) api to limit things to just private or internal (limiting things to only the projects the token can see), but I …
> Add config param `all` to enable syncing all projects in GitLab instance

- CHANGELOG.md
- packages/web/src/app/components/repositoryCarousel.tsx
- packages/web/src/app/repos/columns.tsx
- packages/web/src/app/repos/repositoryTable.tsx
- packages/web/src/app/search/components/codePreviewPanel/index.tsx
- packages/web/src/app/search/components/filterPanel/entry.tsx
- packages/web/src/app/search/components/filterPanel/index.tsx
- packages/web/src/app/search/components/searchResultsPanel/fileMatchContainer.tsx
- packages/web/src/app/search/components/searchResultsPanel/index.tsx
- packages/web/src/app/search/page.tsx
- packages/web/src/lib/schemas.ts
- packages/web/src/lib/utils.ts
This PR makes it s.t, we surface icons and links for self-hosted repositories in various places were we already had support for hosted versions. For example:
Repo carousel icons:
Filter panel icons:
Search result icons:
File links:
Closes #25
> Icon & link support for self-hosted repositories

- README.md
- packages/backend/src/gerrit.ts
- packages/backend/src/main.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/utils.ts
- packages/web/public/gerrit.svg
- packages/web/src/lib/utils.ts
- schemas/v2/index.json
This commit adds support for gerrit repo indexing.
It supports globs for both including and excluding repos.
It does not support branches or tags (as these are going to be reworked by brendan in the future.
It does not support auth yet (I'd need to spin up my own gerrit instance to test this out) - I can add this later hopefully.
Example URLs for experimentation:
// https://chromium-review.googlesource.com
// https://review.opendev.org
// https://android-review.googlesource.com
Sample config:
```
{
"repos": [
{
"type": "gerrit",
"url": "https://gerrit-review.googlesource.com/",
"projects": [
"apps/**",
"gerrit**",
// "modules/**",
"zuul/**"
],
"exclude": {
"projects": [
"gerrit-**"
]
}
}
]
}
```
> Gerrit sync

- packages/web/src/app/search/components/filterPanel/entry.tsx
- packages/web/src/app/search/components/filterPanel/filter.tsx
- packages/web/src/app/search/components/filterPanel/index.tsx
- packages/web/src/app/search/page.tsx
- packages/web/src/components/ui/resizable.tsx
This fixes a couple things which seemed to not be working with the filter results panel:
1. It makes the filter result panel 100% of parent height, and set the repo filtering to be at max 50%. It then lets the language filter fill the remaining height.
2. This fixes the repo display name text such that it does not split with long repo names onto multiple lines, instead showing an ellipsis and gracefully being cut off.
It also puts the count into a box.
3. It also adds cutoff for both search bars to display the number of languages/ repos matched, and cut them off at 100.
In this case the text becomes 100+
4. Do the same for the result counts but cut them off at 999. It makes the text 999+
Before:
After:
Before:
After:
> Filter results css

- README.md
Small PR - Commit fc8815d135308fd3bbbae6023b4d99d985694b86 moved the `posthogProvider.tsx ` file. This PR adjusts sources to changes.
> Update `posthogProvider.tsx` reference

- packages/backend/src/gerrit.ts
- packages/backend/src/schemas/v2.ts
In some cases gerrit will limit the number of projects returned by /projects endpoint, forcing the client to paginate their request to get all projects.
This fulfills this requirement to get all projects
> fix: make gerrit repo fetching paginated

- CHANGELOG.md
- packages/backend/src/constants.ts
- packages/backend/src/db.test.ts
- packages/backend/src/db.ts
- packages/backend/src/main.test.ts
- packages/backend/src/main.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- packages/backend/src/zoekt.ts
- schemas/v2/index.json
This PR adds the `settings.maxFileSize` option to the config schema, which allows users to specify the maximum file size (in bytes) that zoekt should index. E.g.,
```jsonc
{
"settings": {
"maxFileSize": 4194304 // Set size to 4MB (default 2MB)
}
// ...
}
```
All repositories in the config will use this file limit when indexing.
> Add config option to specify max file size

- CHANGELOG.md
- configs/filter.json
- packages/backend/src/github.ts
- packages/backend/src/gitlab.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- packages/backend/src/utils.test.ts
- packages/backend/src/utils.ts
- schemas/v2/index.json
This PR adds the ability to filter what repos are indexed based on the topics that do/don't exist on a given repo. E.g.,:
```jsonc
{
"repos": [
{
"type": "github",
"orgs": [
"sourcebot-dev"
],
// Include repositories in `sourcebot-dev` that have at least one of these topics.
"topics": [
"hacktoberfest",
"advent_of_code"
],
"exclude": {
// Explicitly exclude a topic from being indexed.
"topics": [
"TypeScript"
]
}
}
}
}
```
In the above case, a repo with the label `hacktoberfest` will be indexed, but a repo with both `hacktoberfest` and `TypeScript` will not be indexed.
Fixes #107 
TODO:
- Add usage examples
> Add `topics` and `exclude.topics` to GitHub & GitLab config

- CHANGELOG.md
- packages/backend/package.json
- packages/backend/src/constants.ts
- packages/backend/src/db.test.ts
- packages/backend/src/db.ts
- packages/backend/src/github.ts
- packages/backend/src/gitlab.ts
- packages/backend/src/main.test.ts
- packages/backend/src/main.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- schemas/v2/index.json
- yarn.lock
This PR adds the option `autoDeleteStaleRepos` to the `settings` object of the config. Its default is **true**. When enabled, stale repositories (i.e., the `.zoekt` index files in `.sourcebot/index`, and the checked out repository in `.sourcebot/repos`) are deleted from disk.
Fixes #39 
Also Fixes #127
> Add `autoDeleteStaleRepos` config option

- CHANGELOG.md
- demo-site-config.json
- packages/backend/src/constants.ts
- packages/backend/src/db.test.ts
- packages/backend/src/db.ts
- packages/backend/src/main.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- schemas/v2/index.json
This PR makes it s.t., the reindex interval and resync interval are configurable via `config.settings`:
```jsonc
{
"settings": {
"autoDeleteStaleRepos": true,
"reindexInterval": 3600000,
"resyncInterval": 86400000
},
...
}
```
> Add `reindexInterval` and `resyncInterval` to config settings

- CHANGELOG.md
- demo-site-config.json
- packages/backend/src/github.ts
- packages/backend/src/schemas/v2.ts
- packages/backend/src/types.ts
- schemas/v2/index.json
This PR adds the ability to exclude GitHub repositories based on their disk usage. E.g.,:
```jsonc
{
"repos": [
{
"type": "github",
"repos": [
"sourcebot-dev/sourcebot"
],
"exclude": {
"size": {
"min": 16000, // 16 KB
"max": 1000000000 // 1GB
}
}
}
]
}
```
> [GitHub] Add `exclude.size` property to the config

- CHANGELOG.md
- packages/backend/src/gerrit.ts
- packages/backend/src/gitea.ts
- packages/backend/src/github.ts
- packages/backend/src/gitlab.ts
- packages/backend/src/logger.ts
- packages/backend/src/main.ts
- packages/backend/src/posthogEvents.ts
- yarn.lock
The following adds graceful error handling for code host api calls. When a api call fails, an error message is raised and the config synchronization continues. Fixes #140
The side-effect of this is that if an api experiences some transient error (e.g., network issue, rate limits, etc.), then repositories will be marked stale when they actually are not. If `autoDeleteStaleRepos` is enabled, then the repo & it's index will be deleted.
Two things we can do come to mind:
1. We add a delay between when a repo is marked stale and when it is deleted. This way, it gives the config a change to be re-synced again (and the transient issues gone).
2. We add retry mechanisms to api calls s.t., we retry on known failures.
> Graceful error handling when calling code host apis

- CHANGELOG.md
- packages/web/package.json
- packages/web/src/app/browse/[...path]/codePreview.tsx
- packages/web/src/app/browse/[...path]/contextMenu.tsx
- packages/web/src/app/browse/[...path]/page.tsx
- packages/web/src/app/components/editorContextMenu.tsx
- packages/web/src/app/components/fireHeader.tsx
- packages/web/src/app/components/pageNotFound.tsx
- packages/web/src/app/components/settingsDropdown.tsx
- packages/web/src/app/components/topBar.tsx
- packages/web/src/app/not-found.tsx
- packages/web/src/app/search/components/codePreviewPanel/codePreview.tsx
- packages/web/src/app/search/components/codePreviewPanel/index.tsx
- packages/web/src/app/search/components/searchResultsPanel/fileMatchContainer.tsx
- packages/web/src/app/search/page.tsx
- packages/web/src/hooks/useKeymapExtension.ts
- packages/web/src/lib/posthogEvents.ts
- packages/web/src/lib/schemas.ts
- packages/web/src/lib/server/searchService.ts
- yarn.lock
This PR adds share links to Sourcebot, allowing you to link to a region of code:
https://github.com/user-attachments/assets/e5bb5497-ff29-4ebc-aa2b-b53a5c2f41cf
A future enhancement will be to make the links permanent by using the git SHA as the revision.
Fixes #15
> Share links

- packages/web/src/app/page.tsx
Adds basic footer to the bottom of the homepage:
> Add footer to homepage

- CHANGELOG.md
- entrypoint.sh
This PR adds some error handling in `entrypoint.sh` s.t., we don't immediately crash if a curl command fails when sending a PostHog event for install / upgrade.
How tested:
- Manually tested success & failure case
Fixes #150
Fixes #100
> curl error handling in entrypoint.sh

- CHANGELOG.md
- packages/web/package.json
- packages/web/src/app/components/fireHeader.tsx
- packages/web/src/app/components/keyboardShortcutHint.tsx
- packages/web/src/app/components/repositoryCarousel.tsx
- packages/web/src/app/components/searchBar/searchBar.tsx
- packages/web/src/app/components/searchBar/searchSuggestionsBox.tsx
- packages/web/src/app/components/syntaxReferenceGuide.tsx
- packages/web/src/app/layout.tsx
- packages/web/src/app/page.tsx
- packages/web/src/app/search/components/filterPanel/index.tsx
- packages/web/src/components/ui/dialog.tsx
- packages/web/src/lib/utils.ts
- yarn.lock
This PR adds a reference guide for the query syntax that can be brought up anywhere in the app by using the hotkey "cmd+/" (or "ctr+/" on windows).
TODO:
> Syntax reference guide

- package.json
- packages/web/src/actions.ts
- packages/web/src/app/api/(server)/repos/route.ts
- packages/web/src/app/api/(server)/search/route.ts
- packages/web/src/app/api/(server)/source/route.ts
- packages/web/src/app/browse/[...path]/page.tsx
- packages/web/src/app/page.tsx
- packages/web/src/app/repos/page.tsx
- packages/web/src/app/repos/repositoryTable.tsx
- packages/web/src/app/secrets/page.tsx
- packages/web/src/auth.ts
- packages/web/src/lib/schemas.ts
- packages/web/src/lib/server/searchService.ts
NOTE: this PR will break non-auth mode since it expects an auth session to exist for search and repoList endpoints!
- Run `yarn dev:mt` to run with tenancy enforced
- This will result in repos being indexed with tenancyId's, and all future searches and repo list calls to only return results for repos owned by the org
> enforce tenancy on search and repo listing endpoints

- packages/backend/src/connectionManager.ts
- packages/backend/src/constants.ts
- packages/backend/src/main.ts
- packages/backend/src/repoManager.ts
- packages/backend/src/types.ts
- packages/backend/src/utils.ts
- packages/backend/src/zoekt.ts
- Automatically deletes data for repos that have no connections, and then deletes repo from the DB
- Adds all the logic behind new `RepoManager`
> adds garbage collection for repos

- entrypoint.sh
- packages/web/src/auth.ts
This PR:
- Adds a step to the `entrypoint.sh` to generate a token for authjs if one is not provided via `AUTH_SECRET`.
- Adds `trustHost: true` to the auth config s.t., we don't need to pass `AUTH_TRUST_HOST` (see: https://authjs.dev/getting-started/deployment#docker)
- Excludes providers if the necessary client id / secret are not provided.
> Generate `AUTH_SECRET` if not provided

- Dockerfile
- grafana.alloy
- packages/backend/package.json
- packages/backend/src/main.ts
- packages/backend/src/promClient.ts
- packages/backend/src/repoManager.ts
- supervisord.conf
- yarn.lock
- Sets up grafana alloy to automatically pull zoekt metrics and push to grafana instance. Env vars:
- GRAFANA_ENVIRONMENT
- GRAFANA_ENDPOINT
- GRAFANA_USERNAME
- GRAFANA_PASSWORD
- TODO: add additional internal sourcebot prometheus metrics and push that as well
> add grafana alloy config and setup

- packages/web/src/actions.ts
- packages/web/src/app/[domain]/onboard/components/inviteTeam.tsx
- packages/web/src/app/[domain]/settings/(general)/components/changeOrgDomainCard.tsx
- packages/web/src/app/[domain]/settings/(general)/components/changeOrgNameCard.tsx
- packages/web/src/app/[domain]/settings/(general)/page.tsx
- packages/web/src/app/[domain]/settings/billing/changeBillingEmailCard.tsx
- packages/web/src/app/[domain]/settings/billing/manageSubscriptionButton.tsx
- packages/web/src/app/[domain]/settings/billing/page.tsx
- packages/web/src/app/[domain]/settings/members/components/inviteMemberCard.tsx
- packages/web/src/app/onboard/components/orgCreateForm.tsx
- packages/web/src/lib/posthogEvents.ts
- packages/web/src/lib/schemas.ts
General settings to manage org name and domain (url):
> General settings + cleanup

- packages/web/src/app/[domain]/browse/[...path]/codePreview.tsx
- packages/web/src/app/[domain]/browse/[...path]/page.tsx
- packages/web/src/app/[domain]/components/configEditor.tsx
- packages/web/src/app/[domain]/components/fileHeader.tsx
- packages/web/src/app/[domain]/search/components/codePreviewPanel/codePreview.tsx
- packages/web/src/app/[domain]/search/components/codePreviewPanel/index.tsx
- packages/web/src/app/[domain]/search/components/filterPanel/entry.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/codePreview.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/fileMatchContainer.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/index.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/lightweightCodeMirror.tsx
- packages/web/src/app/[domain]/search/page.tsx
- packages/web/src/app/api/(client)/client.ts
- packages/web/src/hooks/useCodeMirrorTheme.ts
> Dark theme improvements

- .env.development
- package.json
- packages/backend/package.json
- packages/backend/src/env.ts
- packages/backend/src/index.ts
- packages/backend/src/posthog.ts
- packages/crypto/package.json
- packages/web/src/app/posthogProvider.tsx
- packages/web/src/auth.ts
- packages/web/src/env.mjs
- yarn.lock
**Problem:** We had multiple `.env` and `.env.local` files throughout the project used for local development, making it hard to reason about what environment variables were set.
**Solution:** This PR centralizes all **development** environment variables into `.env.development` and `.env.development.local`, the ladder being gitignored. These files are loaded when running `yarn dev` from the root directory by the `with-env` command (which uses [dotenv-cli](https://www.npmjs.com/package/dotenv-cli)). Env vars are cascaded, so any environment variables placed into `.env.development.local` will override `.env.development`. System environment variables **are not** overridden.
> Centralized development env-var management

- packages/backend/src/env.ts
- packages/web/src/env.mjs
**Problem:** Environment variables are treated as strings, even when they look like numbers (e.g., `MY_VAR=42`, 42 will be of type `string`, not `number`). This creates runtime env var validation errors.
**Solution:** Use [z.coerce](https://zod.dev/?id=coercion-for-primitives) to coerce strings into numbers when we expect them to be.
> (fix) Environment variable type massaging for numbers

- Dockerfile
- entrypoint.sh
- packages/backend/src/connectionManager.ts
- packages/backend/src/constants.ts
- packages/backend/src/github.ts
- packages/backend/src/gitlab.ts
- packages/backend/src/repoManager.ts
- packages/db/prisma/migrations/20250325161848_add_is_declarative_flag_to_connection/migration.sql
- packages/db/prisma/schema.prisma
- packages/schemas/src/v3/index.schema.ts
- packages/schemas/src/v3/index.type.ts
- packages/web/src/app/error.tsx
- packages/web/src/initialize.ts
- schemas/v3/index.json
- supervisord.conf
- Added `isDeclarative` flag to the `Connection` table, allowing us to determine if a connection is declaratively defined or not.
- Added logic to delete any declarative connections if they are no longer included in the config.
- Added persistence for Redis - it will now write to `.sourcebot/redis`.
- Changed the concurrency settings to be absolute numbers rather than be a multiple of cpu count.
> Declarative connection cleanup + improvements

- CHANGELOG.md
- packages/backend/src/git.ts
Regression was introduced in #483 - the tl;dr is that `git init --bare` + `git fetch` leaves HEAD pointing to a non-existent default branch. This hot fix changes it back to use `git clone` and instead deletes `remote.origin.url` after cloning.
Fixes #487
> fix(worker): Fix "attempting to index 0 total files" zoekt issue

- CHANGELOG.md
- packages/backend/src/bitbucket.ts
Issue: #295 
When fetching repositories from Bitbucket Cloud workspaces with multiple pages of results, Sourcebot fails on the second page with the following error:
```
[dev:backend] 2025-09-09T19:11:45.876Z error: [bitbucket] Failed to get repos for workspace emilabs: Error: Failed to fetch projects for workspace emilabs: {"type":"error","error":{"message":"Resource not found","detail":"There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}
```
This is caused by the Bitbucket Cloud API returning full URLs (e.g., `https://api.bitbucket.org/2.0/repositories/workspace?page=2`) in pagination `next` responses, but `openapi-fetch` expects separate path and query parameters. The …
> fix(bitbucket): Bitbucket Cloud pagination not working beyond first page

- CHANGELOG.md
- packages/backend/src/repoManager.ts
It seems that ADO server doesn't support passing in the PAT in the username field (this may be a quirk in ADO cloud, because it worked in my testing). Set a placeholder username so that the PAT is properly embedded in the password field in the url
Fixes #522
> fix(azure): Set username in azuredevops clone url

- CHANGELOG.md
- packages/mcp/src/schemas.ts
- packages/web/src/actions.ts
- packages/web/src/app/[domain]/components/errorNavIndicator.tsx
- packages/web/src/app/[domain]/components/progressNavIndicator.tsx
- packages/web/src/app/[domain]/repos/columns.tsx
- packages/web/src/app/[domain]/repos/repositoryTable.tsx
- packages/web/src/lib/schemas.ts
This PR optimizes the `getRepos` action by removing a JOIN we were doing on the `Connection` table. In my brief testing, this improves query performance by 2-3x, which should improve initial page load times for large instances.
The side-effect of this is that certain UX elements (repository table, progress/error tracker) no longer link back to a connection.
> chore(web): Remove join on connections for getRepos

- CHANGELOG.md
- packages/web/src/app/[domain]/browse/[...path]/components/pureTreePreviewPanel.tsx
- packages/web/src/app/[domain]/components/pathHeader.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/fileMatch.tsx
- packages/web/src/app/[domain]/search/components/searchResultsPanel/fileMatchContainer.tsx
- packages/web/src/ee/features/codeNav/components/exploreMenu/referenceList.tsx
- packages/web/src/features/fileTree/components/fileTreeItemComponent.tsx
- packages/web/src/features/fileTree/components/pureFileTreePanel.tsx
Converted the following things into links:
- File headers (including breadcrumb dropdown)
- Files & directories in the file tree
- Reference list
Fixes #519 
The last remaining area I would like to turn into links is the code nav buttons (find all refs / defs). These are slightly more complicated, so I'll leave them for a separate PR.
> fix(web): Change buttons into Links in various places

- CHANGELOG.md
- Dockerfile
Fixes git "dubious ownership" errors that occur when there is a mismatch in permissions between the host user (that mounts the `/data` volume) and the container user. This is a quick workaround that we should be able to remove when #510 merges.
Related:
#168 
#523
> fix: Fix git dubious ownership errors
